1 Extract writing to svg file to separate entities
Nutek/blender_export_svg pull request #3
Opened 2023-09-06 15:52 UTC by Nutek

- Collection of helper object for Tag-Attribute-Tree handling
- Replacement of inline code formatting.

2023-09-07 21:22 UTC, kris039 commented
Add test files to subfolder to increase clarity

2023-09-08 11:45 UTC, kris039 requested changes

2023-09-08 11:45 UTC, kris039 commented on test_helpers.py
Misleading file name

2023-09-08 11:45 UTC, kris039 commented on test_helpers.py
"testing_helpers" or something

2023-09-08 11:45 UTC, kris039 commented on test_tags_attributes_tree_format.py
> +    def test_empty_element_with_attributes(self, attributes, expected):
Add test cases for:
- empty strings
- `None` values
- numbers
- special characters

2023-09-08 11:45 UTC, kris039 commented on test_tags_attributes_tree_format.py
> +    def test_some_comment(self, label, expected):
Add cases for:
- `None`
- empty strings
- comment ending sequence

2023-09-08 11:45 UTC, kris039 commented on test_tags_attributes_tree_format.py
> +    def test_adding_multiple_attributes(self):
Add cases for:
- empty string
- `None`

2023-09-08 11:45 UTC, kris039 commented on test_tags_attributes_tree_format.py
> +class TestTagsAttributeFormatMultipleAddition:
Add case empty parameter

2023-09-08 11:45 UTC, kris039 commented on test_tags_attributes_tree_format.py
> +            .add_nodes(TAT_Node("inner2"))
Add separate cases for add_node and add_nodes methods

2023-09-08 11:45 UTC, kris039 commented on test_tags_attributes_tree_format.py
> +    def test_contains_empty_element(self):
Add cases for:
- invalid object (ex. string)
- `None`

2023-09-08 11:45 UTC, kris039 commented on test_tags_attributes_tree_format.py
> +    def test_adding_attributes_by_chaining(self):
Add separate cases for add_attr and add_attrs methods

2023-09-08 11:45 UTC, kris039 commented on export_svg_280.py
> +    def add_node(self, tag):
Add name validation

2023-09-08 11:45 UTC, kris039 commented on export_svg_280.py
> +    def add_attr(self, name: str, value):
Add name validation

2023-09-09 22:22 UTC, Nutek commented on test_helpers.py
Done

2023-09-09 22:29 UTC, Nutek commented on test_tags_attributes_tree_format.py
> +    def test_adding_attributes_by_chaining(self):
Method `add_attr` removed

2023-09-09 22:35 UTC, Nutek commented on test_tags_attributes_tree_format.py
> +            .add_nodes(TAT_Node("inner2"))
Method `add_node` removed

2023-09-09 23:36 UTC, Nutek commented on test_tags_attributes_tree_format.py
> +    def test_empty_element_with_attributes(self, attributes, expected):
Done

2023-09-10 12:23 UTC, Nutek commented on test_tags_attributes_tree_format.py
> +    def test_adding_multiple_attributes(self):
Due to removed method `add_attr` those cases are covered by different tests. Please refer to `test_element_raises_exception_for_invalid_type_of_attribute_name` or `test_element_raises_exception_for_invalid_type_of_attribute_value`

2023-09-10 12:47 UTC, Nutek commented on test_tags_attributes_tree_format.py
> +class TestTagsAttributeFormatMultipleAddition:
Done.

2023-09-10 23:18 UTC, Nutek commented on test_tags_attributes_tree_format.py
> +    def test_contains_empty_element(self):
Done

2023-09-10 23:18 UTC, Nutek commented on export_svg_280.py
> +    def add_node(self, tag):
Done

2023-09-10 23:18 UTC, Nutek commented on export_svg_280.py
> +    def add_attr(self, name: str, value):
Done

2023-09-13 20:41 UTC, Nutek commented on test_tags_attributes_tree_format.py
> +    def test_some_comment(self, label, expected):
Done

2023-09-19 10:49 UTC, kris039 approved these changes

2023-09-19 10:49 UTC, merged